__title__ = "gopro-tools"
__description__ = "Zentrale Konstanten für die GoPro-GUI."
__url__ = "https://github.com/RalfPeter/gopro-tools"
__version__ = "1.1.6"
__author__ = "RalfPeter"
__author_email__ = "ralfpeter.bergheim@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2026 RalfPeter"
