__title__ = "rpg_src"
__description__ = "Zentrale Konstanten für die GoPro-GUI."
__url__ = "[https://github.com/](https://github.com/)RalfPeter/rpg_src"
__version__ = "1.0"
__author__ = "RalfPeter"
__author_email__ = "ralfpeter.bergheim@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2026 RalfPeter"
